### PR TITLE
Futurified 0003-test expires header value.

### PR DESCRIPTION
**Pull request by krk**
A possible fix for https://github.com/abarth/http-state/issues/18

### CODE REVIEW

**Comment by inikulin** [comment]
@krk Can you update JSON tests using https://github.com/abarth/http-state/tree/master/tools/test_data_to_json as well, please?

**Comment by abarth** [comment]
Thanks for the patch!  See @inikulin 's comment.

**Comment by krk** [comment]
Thank you for the quick responses.

**Comment by abarth** [comment]
Thanks again!

**Pull request merged**
